name: ams2023
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.5
  - matplotlib=3.5.1
  - netcdf4=1.5.7 
  - ipython=8.6.0
  - notebook=6.5.2
  - cartopy=0.18.0
  - pandas=1.4.2
  - s3fs=2022.5.0
  - xarray=0.20.1
  - metpy=1.3.1
